name: XTerm
version: 0.8.0-dev.0.1
author: Omni Software Systems Inc
description: Dart Console Library for Windows
homepage: www.omnisoftsystems.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  ansicolor: any
dev_dependencies:
